name: ai_forum
channels:
  - conda-forge
  - defaults
dependencies:
  - asgiref=3.10.0=pyhd8ed1ab_0
  - bzip2=1.0.8=hd037594_8
  - ca-certificates=2025.11.12=hbd8a1cb_0
  - cyrus-sasl=2.1.28=ha1cbb27_0
  - django=5.2.8=pyhd8ed1ab_0
  - djangorestframework=3.16.1=pyhd8ed1ab_0
  - icu=75.1=hfee45f7_0
  - krb5=1.21.3=h237132a_0
  - libcxx=21.1.5=hf598326_0
  - libedit=3.1.20250104=pl5321hafb1f1b_0
  - libexpat=2.7.1=hec049ff_0
  - libffi=3.5.2=he5f378a_0
  - liblzma=5.8.1=h39f12f2_2
  - libmpdec=4.0.0=h5505292_0
  - libntlm=1.8=h5505292_0
  - libpq=18.0=h31f7a3a_0
  - libsqlite=3.51.0=h8adb53f_0
  - libzlib=1.3.1=h8359307_2
  - ncurses=6.5=h5e97a16_3
  - openldap=2.6.10=hbe55e7a_0
  - openssl=3.6.0=h5503f6c_0
  - pip=25.3=pyh145f28c_0
  - psycopg2=2.9.10=py314h4449abf_3
  - python=3.14.0=h40d2674_102_cp314
  - python_abi=3.14=8_cp314
  - readline=8.2=h1d1bf99_2
  - sqlparse=0.5.3=pyhd8ed1ab_0
  - tk=8.6.13=h892fb3f_3
  - typing_extensions=4.15.0=pyhcf101f3_0
  - tzdata=2025b=h78e105d_0
  - zstd=1.5.7=h6491c7d_2
  - pip:
      - numpy==2.3.5
      - pgvector==0.4.1
prefix: /opt/anaconda3/envs/ai_forum
